### ISSUE TITLE
Custom Color Theme Corrupts Save Data and Crashes App

### ISSUE THREAD

**Issue by lankm** [lankm/senior-project#16]
There are many issues with selecting a custom theme from the parameters view which causes many app breaking bugs. Figure out what is going on and continue. This is one of the more in depth issues.

There are a couple outcomes that could fix this issue:
**Preferred**: find out the original bug an implement custom themes properly.
**good enough**: remove the option for a custom theme and add many other preset themes.
**lazy**: just remove the ability for custom themes and only have the light and dark themes.

**Comment by Jacobmpp** [comment]
Fixed in feature\refactor-1 by properly using Parameters as a ViewModel that is provided instead of being passed around.
